server:
  port: 8087

spring:
  datasource:
    platform: ${SPRING_DATASOURCE_PLATFORM}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: ${SPRING_DATASOURCE_DRIVER}
  jpa:
    show-sql: false

#logging.level.org.springframework=debug
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace