server:
  port: 8088

spring:
  datasource:
    platform: ${SPRING_DATASOURCE_PLATFORM:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/quick-serve-api-producao}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root123}
    driverClassName: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework: info
      hibernate:
        orm:
          jdbc:
            bind: trace