name: Java CI with Coverage

on:
  push:
    branches:
      - feature/*
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configuração do JDK
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Instalar dependências
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # 4. Executar testes com cobertura
      - name: Build and test
        run: mvn clean verify

      # 5. Gerar relatório JaCoCo (apenas local)
      - name: Generate JaCoCo Report
        run: mvn jacoco:report
